name: Acquire activation file
on:
  push:
    branch:
      - testing-2
  workflow_dispatch: {}
jobs:
  requestManualActivationFile:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: webbertakken/unity-request-manual-activation-file@v2
        id: getManualLicenseFile
        
      - uses: actions/upload-artifact@v2
        with:
          name: Manual Activation File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
      
#   activation:
#     name: Request manual activation file 🔑
#     runs-on:
#       - self-hosted
#     steps:
#       # Request manual activation file
# #       - name: Request manual activation file
# #         id: getManualLicenseFile
# #         uses: game-ci/unity-request-activation-file@v2
#       - name: Unity - Request Activation File
#         uses: game-ci/unity-request-activation-file@v2.0.0

#       # Upload artifact (Unity_v20XX.X.XXXX.alf)
#       - name: Expose as artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: ${{ steps.getManualLicenseFile.outputs.filePath }}
#           path: ${{ steps.getManualLicenseFile.outputs.filePath }}
