name: Automated Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.300
    - name: Install NUnit
      working-directory: ./app
      run: |
        dotnet add app package NUnit
        dotnet add app package NUnit3TestAdapter
    - name: Build and Test
      run: |
        dotnet build
        dotnet test
